#include "satelliteComs.h"
#include <stdint.h>

/******************************************************************************
 * name : satelliteComs
 * 
 * inputs: satelliteComsData (void*)
 * satelliteComsData holds the pointers to the following data:
 * fuelLow: bool representing if the fuel is too low
 * batteryLow: bool representing if the battery is too low
 * solarPanelState: bool representing if the solar panel is deploued
 * batteryLevel: unsigned short representing the battery percentage
 * fuelLevel: unsigned short representing the fuel percentage
 * powerConsumption: unsigned short representing the power consumed by the system.
 * powerGeneration : unsigned short representing the power generated by the system.
 * thrusterCommand: unsigned int 32 bit thruster command
 * 
 * outputs: void
 * 
 * description:
 * 
 * satelliteComs manages the communication from both the Earth to the Satellite and
 * the Satellite back to Earth. The primary communication from the Earth to the Satellite
 * is the thruster command. The primary communication from the Satellite to the Earth are the status
 * variables described above. 
 * 
 * 
 * psuedocode:
 * 
 * if first bit is a 1, update thruster command 
 * else set thruster command to "invalid command" ~0
 * 
 * send status info back to earth
 * 
 * 
 * 
 * 
 *  author: Nick Orlov
*****************************************************************************/ 

void satelliteComs(void* satelliteComsData) {
    SatelliteComsData* data = (SatelliteComsData*) satelliteComsData;

    unsigned int thrusterCommand = *data->thrusterCommand;

    if(/* first bit is a 1 */) {
        thrusterCommand = ~0;
    }
    // Transferring data back to earth
    Serial.println(*data->fuelLow);
    Serial.println(*data->batteryLow);
    Serial.println(*data->solarPanelState);
    Serial.println(*data->batteryLevel);
    Serial.println(*data->fuelLevel);
    Serial.println(*data->powerConsumption);
    Serial.println(*data->powerGeneration);

}