#include "satelliteComs.h"
#include <stdint.h>
#include "thrusterSubsystem.h"

/******************************************************************************
 * name : satelliteComs
 * 
 * inputs: satelliteComsData (void*)
 * satelliteComsData holds the pointers to the following data:
 * fuelLow: bool representing if the fuel is too low
 * batteryLow: bool representing if the battery is too low
 * solarPanelState: bool representing if the solar panel is deploued
 * batteryLevel: unsigned short representing the battery percentage
 * fuelLevel: unsigned short representing the fuel percentage
 * powerConsumption: unsigned short representing the power consumed by the system.
 * powerGeneration : unsigned short representing the power generated by the system.
 * thrusterCommand: unsigned int 32 bit thruster command
 * 
 * outputs: void
 * 
 * description:
 * 
 * satelliteComs manages the communication from both the Earth to the Satellite and
 * the Satellite back to Earth. The primary communication from the Earth to the Satellite
 * is the thruster command. The primary communication from the Satellite to the Earth are the status
 * variables described above. 
 * 
 * 
 * psuedocode:
 * 
 * if first bit is a 1, update thruster command 
 * else set thruster command to "invalid command" ~0
 * 
 * send status info back to earth
 * 
 * 
 * 
 * 
 *  author: Nick Orlov
*****************************************************************************/ 

void satelliteComs(void* satelliteComsData) {
    SatelliteComsData* data = (SatelliteComsData*) satelliteComsData;

    unsigned int thrusterCommand = *data->thrusterCommand;

    if(thrusterCommand & 1) {
        thrusterCommand = THRUSTER_CMD_NONE;
    }
    // Transferring data back to earth
    Serial.print("Fuel Low status is: ");
    printBool(*data->fuelLow);
    Serial.println();
    Serial.print("Battery Low status is: ");
    printBool(*data->batteryLow);
    Serial.println();
    Serial.print("Solar Panel state is: ");
    printBool(*data->solarPanelState);
    Serial.println();
    Serial.print("Battery Level is: ");
    Serial.print(*data->batteryLevel);
    Serial.println();
    Serial.print("Fuel Level is: ");
    Serial.print(*data->fuelLevel);
    Serial.println();
    Serial.print("Power Consumption is: ");
    Serial.print(*data->powerConsumption);
    Serial.println();
    Serial.print("Power Generation is: ");
    Serial.print(*data->powerGeneration);
    Serial.println();
}

void printBool(bool input) {
    if(input) {
        Serial.print("true");
    } else {
        Serial.print("false");
    }
}